
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node streaming-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

# Configure multiple service ports for streaming
[deploy.variables]
NODE_ENV = "production"
PORT = "3001"
RTMP_PORT = "1935"
HLS_PORT = "8888"

# Network configuration for streaming
[deploy.networking]
# Allow external connections to RTMP port
externalPort = 1935
internalPort = 1935
protocol = "TCP"

# HTTP service configuration
[[services]]
name = "api"
type = "web"
port = 3001

# RTMP service configuration  
[[services]]
name = "rtmp"
type = "tcp"
port = 1935
# Railway may need special configuration for non-HTTP ports
allowOrigin = "*"

[env]
NODE_ENV = "production"
PORT = "3001"
RTMP_PORT = "1935"
HLS_PORT = "8888"
# Add Railway-specific environment variables
RAILWAY_HEALTHCHECK_TIMEOUT = "60"
RAILWAY_RESTART_POLICY = "on-failure"
