// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkedbcwomesqxlughssq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZWRiY3dvbWVzcXhsdWdoc3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjcyMTgsImV4cCI6MjA2NTcwMzIxOH0._ICbUpfaDtnari9ClCWkxP_DwT-jaOEKWb0czgJkS6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);